---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: jbar-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    snippets:
      - "sudo chown -R root /usr/share/fonts/MapleMono"
      - "sudo chmod 644 /usr/share/fonts/MapleMono/*"
      - "sudo restorecon -vFr /usr/share/fonts/MapleMono"
      - "sudo fc-cache -v"

  - type: dnf
    repos:
      files:
        - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
        - megasync.repo
      copr:
        - alternateved/keyd
  # - type: script
    # snippets:
      ## Remove pre-installed kmods first
      # - "dnf -y remove kmod-v4l2loopback"
      ## Update the kernel - The akmods module seems to require the latest kernel for nvidia drivers
      # - "dnf -y distro-sync --allowerasing"
      ## Or manually: Matches dnf list --installed | grep kernel
      # - "dnf -y upgrade --allowerasing
      #      kernel
      #      kernel-core
      #      kernel-debug-devel
      #      kernel-devel
      #      kernel-devel-matched
      #      kernel-headers
      #      kernel-modules
      #      kernel-modules-core
      #      kernel-modules-extra
      #      kernel-srpm-macros
      #      kernel-tools
      #      kernel-tools-libs"

  - type: akmods
    base: main
    nvidia-driver: nvidia
    install: []

  - type: dnf
    install:
      packages:
        - https://macdriver.oss-us-west-1.aliyuncs.com/vktablet-3.5.10-2.x86_64.1.rpm # Pen tablet driver.
        - keyd
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-caffeine
        - megasync
        - vivaldi-stable
        - helix
        - chezmoi
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-tweaks
        - gnome-software

  - type: systemd
    system:
      enabled:
        - keyd.service

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
          - net.nokyan.Resources
          - io.github.flattool.Ignition
          - page.tesk.Refine
          - org.keepassxc.KeePassXC
          - org.mozilla.thunderbird_esr
      - scope: user # Also add Flathub user repo
        install:
          - com.super_productivity.SuperProductivity
          - com.valvesoftware.Steam
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
          - io.bassi.Amberol
          - io.mgba.mGBA
          - net.kuribo64.melonDS
          - org.azahar_emu.Azahar
          - org.openttd.OpenTTD
          - org.taisei_project.Taisei

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
